### ISSUE TITLE
Update to equal state with your website.

### ISSUE THREAD

**Issue by Dexus** [coolc0ders/Multilingual-App-Demo#1]
Hello together,
would you like to update your code to the same as the blog post under https://doumer.me/multilingual-xamarin-forms-app/ ? that would be awesome.

Also a question: I have done all the steps in the blog post, but I don't get the resx files with the translations, while I have done the xlf files translated. What is the correct way to get the translation working. I thin the resx files should be translated from the xlf of I'm wrong?

**Comment by DamienDoumer** [comment]
Hi @Dexus  I replied you in the comments on my blog. 
I also updated the code as you wished. I tested and everything works fine, you can try it out
