### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by Dexus** [coolc0ders/Multilingual-App-Demo#3]
Hi @DamienDoumer,
thanks for #1 

But now i clone this repo and update the packages to the latest, add german language translated it and I only get the "Hello everyone" but not my translated "Hallo zusammen".

Neither the `String.Translate()` nor the XAML translation is executed, or provides the translation from the Resx.

At the moment I can't explain why this doesn't work, in other projects with Lazy Resources it works in XAML, but I don't have the C# `String.Translate()` function there that I need.

Thanks for your support.

**Comment by DamienDoumer** [comment]
what is the name of your german resx file ?
It is weird, I tested this a few hours ago and it worked on my device. 
In case you still can't make it work, there is this other approach which should work just fine: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?pivots=windows

**Comment by Dexus** [comment]
> what is the name of your german resx file ?

`Resources.de.resx`
Generated by the Language App Toolkit.

Can you tell me wich version of Visual Studio you currently use? Maybe it has todo with the version... but that is only a shoot into the blue...

**Comment by Dexus** [comment]
Okay, looks like a Xamarin / VS problem:
If i run:
```
// Pass the class name of your resources as a parameter e.g. MyResources for MyResources.resx
            ResourceManager rm = new ResourceManager(typeof(Multilingual.Resources));

            CultureInfo[] cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
            foreach (CultureInfo culture in cultures)
            {
                try
                {
                    ResourceSet rs = rm.GetResourceSet(culture, true, false);
                    // or ResourceSet rs = rm.GetResourceSet(new CultureInfo(culture.TwoLetterISOLanguageName), true, false);
                    string isSupported = (rs == null) ? " is not supported" : " is supported";
                    Console.WriteLine(culture + isSupported);
                }
                catch (CultureNotFoundException exc)
                {
                    Console.WriteLine(culture + " is not available on the machine or is an invalid culture identifier.");
                    Console.WriteLine(exc);
                }
            }
```
with in my MainPage.xaml.cs i only get ` '' is supported and en is supported` which is what is default for me. all other Culture are not supportet. So it looks for me like there is a problem with compiling the ressources into the app.

Thank you.

**Comment by DamienDoumer** [comment]
Hi @Dexus  did you add this in your csproj of the dotnet standard project ?
```
<PropertyGroup> 
 <TargetFramework>netstandard2.0</TargetFramework> 
 <NeutralLanguage>en-US</NeutralLanguage>
</PropertyGroup>

```

**Comment by Dexus** [comment]
My NeutralLanguage is `en`. But it looks like a bug with the xamarin and virsual studio...
